### ISSUE TITLE
Add semantic HTML landmarks

### ISSUE THREAD

**Issue by sano2019** [sano2019/portfolio_react#1]
Portfolio is not really accessible at the moment. Need to add semantic HTML e.g. header, main, nav etc.

**Comment by Hariprasad19036** [comment]
I would like to work on this issue, kindly assign this to me!

**Comment by sano2019** [comment]
You're welcome to work on this @Hariprasad19036. Please make sure you don't submit until October if you want it to count! :) I think that is part of the rules that the PRs must be done during that month

**Comment by hamzailyas237** [comment]
I want to contribute to this issue for the Hactoberfest, can I?

**Comment by sano2019** [comment]
Hi @Hariprasad19036, is this still something you want to work on? If not, I can open up the issue for @hamzailyas237 if he is still interested.

**Comment by Hariprasad19036** [comment]
Hey @sano2019 , I've already raised a PR for it long ago! https://github.com/sano2019/portfolio_react/pull/6

**Comment by sano2019** [comment]
> Hey @sano2019 , I've already raised a PR for it long ago! #6

Ah yes I see that now, I thought it was one where I asked for some changes as the PR didn't cover an issue but that might have been something else. I'll try to get through it and get back to you soon =)

**Comment by sano2019** [comment]
Closed by #6
