### ISSUE TITLE
Add aria labels to project cards

### ISSUE THREAD

**Issue by EmmaDawsonDev** [sano2019/portfolio_react#5]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/57045550/194063902-d81f32f5-f46a-4a4f-ad45-36a23b8b1335.png">

currently all cards have links which will be read out by screen readers as website and github. When there are several links on the same page with the same title you should add aria-labels to them to differentiate for screen reader users. so they don't just hear website website website etc

 eg 

```
<div className='card-button-container'>
        <a
          href={props.url}
          target='_blank'
          rel='noopener noreferrer'
          className='card-button'
         aria-label={`${props.title} website`}
        >
          Website
        </a>

        <a
          href={props.github}
          target='_blank'
          rel='noopener noreferrer'
          className='card-button'
          aria-label={`${props.title} github`}
        >
          Github
        </a>

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by sano2019** [comment]
@Vinitvh Assigned :)
